version: 0.2

phases:
  build:
    commands:
      - echo Compiling and building the project
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/enrollment-system.jar
  discard-paths: yes